<script setup>
import {computed,ref,watch} from 'vue'
import {offlineApi} from '../../api/offline'
import {confidence,number,seconds} from '../../utils/offline'
const props=defineProps({job:Object,summary:Object}),variant=ref('annotated'),error=ref(false)
const url=computed(()=>variant.value==='original'?offlineApi.originalUrl(props.job.job_id):offlineApi.artifactUrl(props.job.job_id,'annotated'))
watch(url,()=>error.value=false)
</script>
<template><div class="offline-result-grid section-gap"><section class="card"><div class="offline-upload-info"><h2>图片检测结果</h2><el-radio-group v-model="variant"><el-radio-button value="original">原图</el-radio-button><el-radio-button value="annotated">标注图</el-radio-button></el-radio-group></div><el-image v-if="!error" class="offline-image" :src="url" :preview-src-list="[url]" preview-teleported fit="contain" @error="error=true"/><el-alert v-else title="图片读取失败，请检查产物完整性或后端连接" type="error" :closable="false"/></section>
<section class="card"><h2>图片统计</h2><el-descriptions :column="1" border><el-descriptions-item label="原尺寸">{{job.input_width}} × {{job.input_height}}</el-descriptions-item><el-descriptions-item label="输出尺寸">{{summary.image?.output_width}} × {{summary.image?.output_height}}</el-descriptions-item><el-descriptions-item label="检测框数量">{{number(summary.detection_count)}}</el-descriptions-item><el-descriptions-item label="疑似违规检测项数">{{number(summary.candidate_count)}}</el-descriptions-item><el-descriptions-item label="类别种类（非零）">{{Object.values(summary.class_counts||{}).filter(v=>v>0).length}}</el-descriptions-item><el-descriptions-item label="处理耗时">{{seconds(summary.processing_seconds)}}</el-descriptions-item></el-descriptions><p class="muted">单张图片只展示候选检测项，不产生 Track ID 或时序确认事件。</p><div v-for="(count,name) in summary.class_counts" :key="name" class="offline-count"><span>{{({person:'人员',hardhat:'安全帽',no_hardhat:'未戴安全帽',vest:'反光衣',no_vest:'未穿反光衣'})[name]||name}}</span><strong>{{count}}</strong></div><p class="muted">机械 / 车辆：未评估</p></section></div><section class="card section-gap"><h2>疑似违规检测项详情</h2><el-table :data="summary.candidates||[]" max-height="300"><el-table-column label="检测类别" min-width="130"><template #default="{row}">{{({person:'人员',hardhat:'安全帽',no_hardhat:'未戴安全帽',vest:'反光衣',no_vest:'未穿反光衣'})[row.class_name]||row.class_name}}</template></el-table-column><el-table-column label="置信度" min-width="120"><template #default="{row}"><el-tooltip :content="String(row.confidence??'未提供')"><span class="offline-confidence">{{confidence(row.confidence)}}</span></el-tooltip></template></el-table-column><el-table-column label="原尺寸坐标" min-width="200"><template #default="{row}">{{row.bbox_xyxy?.join('，')}}</template></el-table-column></el-table></section></template>
