import {createApp,nextTick} from 'vue'
import {createPinia,setActivePinia} from 'pinia'
import ElementPlus,{ElMessageBox} from 'element-plus'
import zhCn from 'element-plus/es/locale/lang/zh-cn'
import {describe,it,expect,vi} from 'vitest'
import OfflineUploader from './OfflineUploader.vue'
import ImagePanel from './ImageDetectionPanel.vue'
import Downloads from './OfflineArtifactDownloads.vue'
import History from './OfflineTaskHistory.vue'
import VideoPanel from './VideoDetectionPanel.vue'
import EventId from './EventId.vue'
import {useOfflineStore} from '../../stores/offline'
import {offlineApi} from '../../api/offline'
function mount(component,props){const root=document.createElement('div');document.body.append(root);const pinia=createPinia();setActivePinia(pinia);const app=createApp(component,props);app.config.warnHandler=()=>{};app.use(pinia);app.use(ElementPlus,{locale:zhCn});const vm=app.mount(root);return {root,app,vm,store:useOfflineStore()}}
describe('offline interactive components',()=>{
 it('copies the complete event ID and reports clipboard refusal',async()=>{const original=Object.getOwnPropertyDescriptor(navigator,'clipboard');const writeText=vi.fn().mockResolvedValue();Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText}});const {root,app}=mount(EventId,{value:'EVT-complete-value'});try{root.querySelector('button').click();await Promise.resolve();await nextTick();expect(writeText).toHaveBeenCalledWith('EVT-complete-value');expect(root.textContent).toContain('已复制');writeText.mockRejectedValue(new Error('denied'));root.querySelector('button').click();await Promise.resolve();await nextTick();expect(root.textContent).toContain('复制失败')}finally{if(original)Object.defineProperty(navigator,'clipboard',original);else delete navigator.clipboard;app.unmount();root.remove()}})

 it('requires explicit audio consent and refusal does not submit',async()=>{const {root,app,vm,store}=mount(OfflineUploader,{type:'video'});store.capabilities={video_processor_available:true,max_video_bytes:100};await nextTick();vm.$.setupState.change({raw:new File(['abc'],'video.mp4',{type:'video/mp4'})});await nextTick();const confirm=vi.spyOn(ElMessageBox,'confirm').mockRejectedValue('cancel');const upload=vi.spyOn(store,'upload').mockResolvedValue();[...root.querySelectorAll('button')].find(b=>b.textContent.includes('开始检测')).click();await nextTick();await Promise.resolve();expect(confirm).toHaveBeenCalledOnce();expect(upload).not.toHaveBeenCalled();confirm.mockRestore();app.unmount();root.remove()})
 it('disabled capability prevents uploads',async()=>{const {root,app,store}=mount(OfflineUploader,{type:'image'});store.capabilities={image_processor_available:false,image_processor_reason:'未授权',max_image_bytes:100};await nextTick();expect(root.textContent).toContain('未授权');expect(root.querySelector('button').disabled).toBe(true);app.unmount();root.remove()})
 it('switches original/annotated with restricted URLs',async()=>{const {root,app}=mount(ImagePanel,{job:{job_id:'abc',input_width:20,input_height:10},summary:{image:{output_width:20,output_height:10},detection_count:2,candidate_count:1}});await nextTick();expect(root.querySelector('img').src).toContain('/artifacts/annotated');root.querySelector('input[value=original]').click();await nextTick();expect(root.querySelector('img').src).toContain('/input-image');expect(root.textContent).toContain('疑似违规检测项数');app.unmount();root.remove()})
 it('download failure remains error, incomplete task stays disabled',async()=>{const props={job:{job_id:'a',status:'PROCESSING'},items:[{key:'results',size_bytes:10}]};const {root,app}=mount(Downloads,props);expect(root.querySelector('button').disabled).toBe(true);app.unmount();root.remove();const next=mount(Downloads,{...props,job:{job_id:'a',status:'COMPLETED'}});const spy=vi.spyOn(offlineApi,'download').mockRejectedValue(new Error('产物损坏'));next.root.querySelector('button').click();await nextTick();await Promise.resolve();await nextTick();expect(next.root.textContent).toContain('产物损坏');spy.mockRestore();next.app.unmount();next.root.remove()})
 it('uses server history pagination and filters',async()=>{const spy=vi.spyOn(offlineApi,'jobs').mockResolvedValue({items:[],total_count:21});const {root,app,vm}=mount(History,{});for(let i=0;i<4;i++)await nextTick();expect(root.textContent).toContain('共 21 条');root.querySelector('button[aria-label="下一页"]').click();for(let i=0;i<4;i++)await nextTick();expect(spy.mock.calls.at(-1)[0].offset).toBe(10);vm.$.setupState.filters.media_type='video';vm.$.setupState.query();await nextTick();expect(spy.mock.calls.at(-1)[0].media_type).toBe('video');spy.mockRestore();app.unmount();root.remove()})
 it('event selection seeks real video seconds and queries owned evidence',async()=>{const event={event_id:'EVT-a',evidence_id:'EVD-a',event_type:'PPE_UNKNOWN',video_timestamp_seconds:8.5,frame_id:255,track_id:1,integrity_status:'VERIFIED',original:{sha256:'a'},annotated:{sha256:'b'}};const list=vi.spyOn(offlineApi,'events').mockResolvedValue({items:[event],total:1});const detail=vi.spyOn(offlineApi,'evidence').mockResolvedValue(event);const {root,app,vm}=mount(VideoPanel,{job:{job_id:'owned'},summary:{event_analysis_status:'COMPLETED',confirmed_events:1}});await vm.$.setupState.choose(event);await nextTick();expect(root.querySelector('video').currentTime).toBe(8.5);expect(detail).toHaveBeenCalledWith('owned','EVD-a');expect(root.textContent).toContain('PPE 状态未知');list.mockRestore();detail.mockRestore();app.unmount();root.remove()})
})
