<script setup>
import {onActivated,onDeactivated,onMounted,onUnmounted,reactive,ref,watch} from 'vue'
import {ElMessage} from 'element-plus'
import {offlineApi} from '../../api/offline'
import {cancellable,eventCount,number,seconds,stateName} from '../../utils/offline'
const emit=defineEmits(['select']),filters=reactive({status:'',media_type:'',dates:[]}),page=ref(1),items=ref([]),total=ref(0),loading=ref(false),error=ref(''),summaries=ref({})
let generation=0,controller
async function load(){const token=++generation;controller?.abort();controller=new AbortController();loading.value=true;error.value='';summaries.value={};try{const result=await offlineApi.jobs({limit:10,offset:(page.value-1)*10,status:filters.status||undefined,media_type:filters.media_type||undefined,start_at:filters.dates?.[0]?new Date(filters.dates[0]).toISOString():undefined,end_at:filters.dates?.[1]?new Date(filters.dates[1]).toISOString():undefined},controller.signal);if(token===generation){items.value=result.items;total.value=result.total_count;await Promise.all(result.items.filter(j=>j.media_type==='video'&&j.status==='COMPLETED'&&j.artifact_keys.includes('summary')).map(async j=>{try{const s=await offlineApi.summary(j.job_id,controller.signal);if(token===generation)summaries.value[j.job_id]=eventCount(s)}catch(e){if(token===generation)summaries.value[j.job_id]='统计读取失败'}}))}}catch(e){if(token===generation)error.value=e.message}finally{if(token===generation)loading.value=false}}
function query(){page.value=1;load()}
async function cancel(id){try{await offlineApi.cancel(id);await load()}catch(e){ElMessage.error(e.message)}}
async function zip(id){try{await offlineApi.download(id,'results')}catch(e){ElMessage.error(e.message)}}
function stop(){generation++;controller?.abort()}
watch(page,load);onMounted(load);onActivated(load);onDeactivated(stop);onUnmounted(stop)
</script>
<template><section class="card"><div class="filters"><el-select v-model="filters.media_type" clearable placeholder="媒体类型"><el-option label="图片" value="image"/><el-option label="视频" value="video"/></el-select><el-select v-model="filters.status" clearable placeholder="任务状态"><el-option v-for="(label,key) in stateName" :key="key" :value="key" :label="label"/></el-select><el-date-picker v-model="filters.dates" type="datetimerange" start-placeholder="开始时间" end-placeholder="结束时间"/><el-button type="primary" @click="query">查询</el-button><el-button @click="load">刷新</el-button></div><el-alert v-if="error" :title="error" type="error" :closable="false"/>
<el-table v-loading="loading" :data="items" max-height="480"><el-table-column prop="job_id" label="Job ID" min-width="190" show-overflow-tooltip/><el-table-column prop="original_filename" label="文件名" min-width="170" show-overflow-tooltip/><el-table-column label="媒体" width="65"><template #default="{row}">{{row.media_type==='image'?'图片':'视频'}}</template></el-table-column><el-table-column label="创建时间" min-width="165"><template #default="{row}">{{new Date(row.created_at).toLocaleString('zh-CN')}}</template></el-table-column><el-table-column label="状态" width="145"><template #default="{row}">{{stateName[row.status]}}</template></el-table-column><el-table-column label="进度" width="80"><template #default="{row}">{{row.progress_percent==null?'—':`${row.progress_percent}%`}}</template></el-table-column><el-table-column label="检测框 / 图片候选" min-width="145"><template #default="{row}">{{number(row.detection_count)}} / {{row.media_type==='image'?number(row.candidate_count):'不适用'}}</template></el-table-column><el-table-column label="确认事件（视频）" min-width="145"><template #default="{row}">{{row.media_type==='video'?(summaries[row.job_id]??'—'):'不适用'}}</template></el-table-column><el-table-column label="耗时" width="95"><template #default="{row}">{{seconds(row.processing_seconds)}}</template></el-table-column><el-table-column label="操作" min-width="180"><template #default="{row}"><el-button link type="primary" @click="emit('select',row.job_id)">查看</el-button><el-button v-if="row.status==='COMPLETED'&&row.artifact_keys.includes('results')" link @click="zip(row.job_id)">ZIP</el-button><el-button v-if="cancellable.has(row.status)" link type="danger" @click="cancel(row.job_id)">取消</el-button></template></el-table-column></el-table><el-pagination class="pagination" v-model:current-page="page" :page-size="10" :total="total" layout="prev,pager,next,total"/><p class="muted">视频确认事件统计请打开任务结果查看；历史 D 任务会明确显示未执行事件分析。</p></section></template>
