<script setup>
import {computed,onUnmounted,ref,watch} from 'vue'
import {offlineApi} from '../../api/offline'
import EventId from './EventId.vue'
import {confidence,eventCount,eventName,number,seconds,timelinePosition} from '../../utils/offline'
const props=defineProps({job:Object,summary:Object}),video=ref(),page=ref(1),filter=ref(''),events=ref([]),total=ref(0),timeline=ref([]),selected=ref(null),variant=ref('annotated'),error=ref(''),evidenceError=ref(''),loading=ref(false),duration=ref(0),playerError=ref(false)
let generation=0,controller,timelineController
const analyzed=computed(()=>props.summary.event_analysis_status==='COMPLETED')
const videoUrl=computed(()=>offlineApi.artifactUrl(props.job.job_id,'annotated'))
const imageUrl=computed(()=>selected.value?offlineApi.evidenceUrl(props.job.job_id,selected.value.evidence_id,variant.value):'')
async function load(){const token=++generation;controller?.abort();controller=new AbortController();error.value='';loading.value=true;try{const result=await offlineApi.events(props.job.job_id,{limit:10,offset:(page.value-1)*10,event_type:filter.value||undefined},controller.signal);if(token===generation){events.value=result.items;total.value=result.total}}catch(e){if(token===generation)error.value=e.message}finally{if(token===generation)loading.value=false}}
async function allEvents(){timelineController?.abort();timelineController=new AbortController();const signal=timelineController.signal;let offset=0,rows=[];const id=props.job.job_id;try{while(true){const result=await offlineApi.events(id,{limit:100,offset},signal);if(id!==props.job.job_id)return;rows.push(...result.items);offset+=result.items.length;if(offset>=result.total||!result.items.length)break}timeline.value=rows.sort((a,b)=>a.video_timestamp_seconds-b.video_timestamp_seconds)}catch(e){if(!signal.aborted&&id===props.job.job_id)error.value=e.message}}
watch(()=>props.job.job_id,()=>{selected.value=null;events.value=[];timeline.value=[];page.value=1;filter.value='';playerError.value=false;if(analyzed.value){load();allEvents()}},{immediate:true})
watch(filter,()=>{page.value=1;load()})
watch(page,load)
watch(imageUrl,()=>evidenceError.value='')
async function choose(event){selected.value=event;variant.value='annotated';evidenceError.value='';if(video.value)video.value.currentTime=event.video_timestamp_seconds;try{const detail=await offlineApi.evidence(props.job.job_id,event.evidence_id);if(selected.value?.event_id===event.event_id)selected.value=detail}catch(e){if(selected.value?.event_id===event.event_id)evidenceError.value=e.message}}
onUnmounted(()=>{generation++;controller?.abort();timelineController?.abort()})
</script>
<template><div class="offline-result-grid section-gap"><section class="card"><h2>原分辨率标注视频</h2><video ref="video" class="offline-video" :src="videoUrl" controls preload="metadata" @loadedmetadata="duration=video.duration" @error="playerError=true"/><el-alert v-if="playerError" title="视频读取或解码失败，请检查连接、产物完整性及浏览器H.264支持" type="error" :closable="false"/><p class="muted">{{summary.input_width}} × {{summary.input_height}} · {{summary.source_fps}} FPS · {{seconds(duration||job.input_duration_seconds)}} · {{summary.source_has_audio?'源视频含音轨，输出已移除':'源视频无音轨'}} · H.264</p>
<h2>事件时间轴</h2><div v-if="analyzed&&timeline.length&&duration" class="offline-timeline"><button v-for="event in timeline" :key="event.event_id" :title="`${eventName[event.event_type]} · ${seconds(event.video_timestamp_seconds)}`" :style="{left:`${timelinePosition(event,duration)}%`}" :aria-label="`${eventName[event.event_type]} · ${seconds(event.video_timestamp_seconds)}`" :aria-pressed="selected?.event_id===event.event_id" :class="[event.event_type,{selected:selected?.event_id===event.event_id}]" @click="choose(event)"><span>{{seconds(event.video_timestamp_seconds)}}</span></button></div><el-empty v-else :description="analyzed?'视频内暂无确认事件':'该任务未执行事件分析'" :image-size="45"/>
</section><section class="card"><h2>视频统计</h2><el-descriptions :column="1" border><el-descriptions-item label="总帧 / 已处理">{{number(job.total_frames)}} / {{number(job.processed_frames)}}</el-descriptions-item><el-descriptions-item label="累计检测框">{{number(summary.detection_count)}}</el-descriptions-item><el-descriptions-item label="任务内轨迹 ID 数">{{number(summary.unique_track_ids)}}</el-descriptions-item><el-descriptions-item label="确认事件数">{{eventCount(summary)}}</el-descriptions-item><el-descriptions-item label="PPE 状态未知事件">{{analyzed?number(summary.events_by_type?.PPE_UNKNOWN??0):'未执行事件分析'}}</el-descriptions-item><el-descriptions-item label="未知关联观测">{{number(summary.unknown_associations)}}</el-descriptions-item><el-descriptions-item label="证据图片文件数">{{number(summary.evidence_image_files)}}</el-descriptions-item><el-descriptions-item label="处理耗时">{{seconds(summary.processing_seconds)}}</el-descriptions-item></el-descriptions><p class="muted">轨迹 ID 为本任务跟踪编号，不等于独立人员数。未知关联观测不等于未知事件。机械 / 车辆：未评估。</p></section></div>
<section v-if="analyzed" class="card section-gap"><div class="offline-upload-info"><h2>确认事件 · 只读</h2><el-select v-model="filter" clearable placeholder="全部事件类型" style="width:190px"><el-option v-for="(label,key) in eventName" :key="key" :value="key" :label="label"/></el-select></div><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-table v-loading="loading" :data="events" max-height="350" @row-click="choose"><el-table-column label="事件 ID" min-width="240"><template #default="{row}"><EventId :value="row.event_id"/></template></el-table-column><el-table-column label="事件类型" min-width="150"><template #default="{row}">{{eventName[row.event_type]}}</template></el-table-column><el-table-column prop="track_id" label="Track ID" width="90"/><el-table-column label="置信度" width="100"><template #default="{row}"><el-tooltip :content="String(row.confidence??'未提供')"><span class="offline-confidence">{{confidence(row.confidence)}}</span></el-tooltip></template></el-table-column><el-table-column prop="frame_id" label="触发帧" width="85"/><el-table-column label="视频时间" width="100"><template #default="{row}">{{seconds(row.video_timestamp_seconds)}}</template></el-table-column><el-table-column label="证据" width="100"><template #default="{row}">{{row.integrity_status==='VERIFIED'?'已验证':row.integrity_status}}</template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click.stop="choose(row)">定位与证据</el-button></template></el-table-column></el-table><el-pagination class="pagination" v-model:current-page="page" :page-size="10" :total="total" layout="prev,pager,next,total"/></section>
<section v-if="selected" class="card section-gap"><div class="offline-upload-info"><h2>关键证据</h2><el-radio-group v-model="variant"><el-radio-button value="original">原图</el-radio-button><el-radio-button value="annotated">标注图</el-radio-button></el-radio-group></div><div class="offline-result-grid"><div><el-image v-if="!evidenceError" class="offline-image" :src="imageUrl" :preview-src-list="[imageUrl]" preview-teleported fit="contain" @error="evidenceError='证据读取失败，完整性或连接异常'"/><el-alert v-else :title="evidenceError" type="error" :closable="false"/></div><div><p>{{eventName[selected.event_type]}} · Track ID {{selected.track_id}}</p><p>触发帧 {{selected.frame_id}} · {{seconds(selected.video_timestamp_seconds)}}</p><p>事件 {{selected.event_id}}</p><p>证据 {{selected.evidence_id}}</p><el-tag :type="!evidenceError&&selected.integrity_status==='VERIFIED'?'success':'danger'">{{evidenceError?'证据不可用':selected.integrity_status==='VERIFIED'?'服务端完整性已验证':'未验证'}}</el-tag><p class="muted">SHA256（{{variant==='original'?'原图':'标注图'}}）</p><code class="offline-hash">{{selected[variant]?.sha256}}</code></div></div></section>
</template>
