import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest'
import {createPinia,setActivePinia} from 'pinia'
const api=vi.hoisted(()=>({capabilities:vi.fn(),job:vi.fn(),summary:vi.fn(),artifacts:vi.fn(),upload:vi.fn(),cancel:vi.fn()}))
vi.mock('../api/offline',()=>({offlineApi:api}))
import {useOfflineStore} from './offline'
import {validateFile,eventCount,timelinePosition,eventName,cancellable} from '../utils/offline'
describe('offline state and server contracts',()=>{
 beforeEach(()=>{setActivePinia(createPinia());vi.clearAllMocks();sessionStorage.clear();vi.useFakeTimers();api.capabilities.mockResolvedValue({image_processor_available:true});api.job.mockResolvedValue({job_id:'a',media_type:'video',status:'PROCESSING'});api.summary.mockResolvedValue({confirmed_events:null,event_analysis_status:'NOT_IMPLEMENTED'});api.artifacts.mockResolvedValue({items:[]})})
 afterEach(()=>vi.useRealTimers())
 it('uses genuine limits and rejects wrong/empty media',()=>{const caps={max_image_bytes:10,max_video_bytes:20};expect(validateFile({name:'a.png',size:10},'image',caps)).toBe('');expect(validateFile({name:'a.png',size:11},'image',caps)).toContain('超出');expect(validateFile({name:'a.jpg',size:1},'video',caps)).toContain('MP4');expect(validateFile({name:'a.mp4',size:0},'video',caps)).toContain('不能为空')})
 it('does not format old D null results as zero',()=>{expect(eventCount({confirmed_events:null,event_analysis_status:'NOT_IMPLEMENTED'})).toBe('未执行事件分析');expect(eventCount({confirmed_events:0,event_analysis_status:'COMPLETED'})).toBe(0);expect(eventName.PPE_UNKNOWN).toBe('PPE 状态未知')})
 it('positions timeline by video seconds rather than list index',()=>{expect(timelinePosition({video_timestamp_seconds:8.5},20)).toBe(42.5);expect(timelinePosition({},20)).toBeNull()})
 it('runs one poll loop, preserves tab changes and stops on deactivation',async()=>{const s=useOfflineStore();await s.select('a');s.tab='history';await vi.advanceTimersByTimeAsync(1500);expect(s.tab).toBe('history');expect(api.job).toHaveBeenCalledTimes(2);s.stop();await vi.advanceTimersByTimeAsync(5000);expect(api.job).toHaveBeenCalledTimes(2)})
 it('stops polling only after final server status and loads manifest',async()=>{api.job.mockResolvedValue({job_id:'a',media_type:'video',status:'COMPLETED'});const s=useOfflineStore();await s.select('a');await vi.advanceTimersByTimeAsync(5000);expect(api.job).toHaveBeenCalledTimes(1);expect(s.summary.confirmed_events).toBeNull();expect(api.artifacts).toHaveBeenCalledOnce();s.stop()})
 it('ignores a stale response after selecting another job',async()=>{let resolve;api.job.mockImplementationOnce(()=>new Promise(r=>resolve=r));const s=useOfflineStore();const old=s.select('old');api.job.mockResolvedValue({job_id:'new',media_type:'image',status:'FAILED'});await s.select('new');resolve({job_id:'old',media_type:'video',status:'COMPLETED'});await old;expect(s.job.job_id).toBe('new');s.stop()})
 it('restores job id and obtains authoritative server state',async()=>{sessionStorage.setItem('offline_job_id','a');const s=useOfflineStore();await s.activate();expect(api.job).toHaveBeenCalledWith('a',expect.anything());s.stop()})
 it('keeps HTTP failures explicit and never substitutes data',async()=>{api.job.mockRejectedValue(new Error('后端断线'));const s=useOfflineStore();await s.select('a');expect(s.error).toBe('后端断线');expect(s.job).toBeNull();s.stop()})
 it('uses actual upload bytes and prevents double submit',async()=>{let resolve;api.upload.mockImplementation((file,confirmed,progress)=>{expect(confirmed).toBe(true);progress({loaded:5,total:10});return new Promise(r=>resolve=r)});const s=useOfflineStore();const work=s.upload(new File(['x'],'x.mp4'),true);expect(s.uploadPercent).toBe(50);await s.upload(new File(['x'],'x.mp4'),true);expect(api.upload).toHaveBeenCalledOnce();resolve({job_id:'a'});await work;s.stop()})
 it('cancel updates only corresponding task and respects enum',async()=>{const s=useOfflineStore();await s.select('a');api.cancel.mockResolvedValue({job_id:'a',status:'CANCELLING'});await s.cancel('a');expect(s.job.status).toBe('CANCELLING');expect(cancellable.has('COMPLETED')).toBe(false);s.stop()})
 it.each([404,409,422])('retains server error %i without fake completed data',async status=>{api.job.mockRejectedValue(Object.assign(new Error(`HTTP ${status}`),{status}));const s=useOfflineStore();await s.select('a');expect(s.error).toContain(String(status));expect(s.summary).toBeNull();s.stop()})
 it('keeps unknown upload total indeterminate',async()=>{api.upload.mockImplementation(async(f,c,progress)=>{progress({loaded:5});return {job_id:'a',media_type:'video',status:'QUEUED'}});const s=useOfflineStore();await s.upload(new File(['x'],'a.mp4'),false);expect(s.uploadPercent).toBeNull();expect(s.active).toBe(false);expect(s.timer).toBeNull()})
})
