from utils.paths import PROJECT_ROOT


REQUIRED_DIRECTORIES = [
    "configs",
    "scripts",
    "core/detection",
    "core/tracking",
    "core/association",
    "core/rules",
    "core/events",
    "core/pipeline",
    "services",
    "infra/database",
    "infra/storage",
    "infra/tts",
    "infra/llm",
    "web/pages",
    "web/components",
    "utils",
    "data/external",
    "data/raw",
    "data/interim",
    "data/processed",
    "data/samples",
    "models/pretrained",
    "models/checkpoints",
    "models/best",
    "models/exports",
    "artifacts/runs",
    "artifacts/reports",
    "artifacts/events/snapshots",
    "artifacts/events/videos",
    "artifacts/logs",
    "tests/unit",
    "tests/integration",
    "tests/e2e",
    "tests/regression",
    "tests/fixtures",
    "docs/phases",
]

REQUIRED_FILES = [
    "AGENTS.md",
    "README.md",
    "requirements.txt",
    "pyproject.toml",
    ".gitignore",
    "configs/app.yaml",
    "configs/dataset.yaml",
    "configs/train.yaml",
    "configs/inference.yaml",
    "configs/tracker.yaml",
    "configs/rules.yaml",
    "scripts/prepare_dataset.py",
    "scripts/validate_dataset.py",
    "scripts/train.py",
    "scripts/evaluate.py",
    "scripts/infer_image.py",
    "scripts/infer_video.py",
    "scripts/infer_stream.py",
    "scripts/run_demo.py",
    "core/detection/detector.py",
    "core/detection/schemas.py",
    "core/tracking/tracker.py",
    "core/association/ppe_person_association.py",
    "core/rules/compliance_engine.py",
    "core/rules/temporal_filter.py",
    "core/events/event_engine.py",
    "core/events/event_state.py",
    "core/pipeline/inference_pipeline.py",
    "services/dataset_service.py",
    "services/train_service.py",
    "services/val_service.py",
    "services/inference_service.py",
    "services/tracking_service.py",
    "services/compliance_service.py",
    "services/event_service.py",
    "services/report_service.py",
    "services/agent_service.py",
    "infra/database/schema.sql",
    "infra/database/database.py",
    "infra/database/repository.py",
    "infra/storage/snapshot_storage.py",
    "infra/storage/video_storage.py",
    "infra/tts/tts_service.py",
    "infra/llm/llm_client.py",
    "infra/llm/fallback.py",
    "web/Home.py",
    "web/pages/1_实时监控.py",
    "web/pages/2_图片检测.py",
    "web/pages/3_视频检测.py",
    "web/pages/4_违规事件.py",
    "web/pages/5_数据大屏.py",
    "web/pages/6_AI报告.py",
    "web/pages/7_AI助手.py",
    "utils/paths.py",
    "utils/config_loader.py",
    "utils/logging_utils.py",
    "utils/performance_utils.py",
    "utils/image_utils.py",
    "utils/system_utils.py",
    "data/README.md",
    "tests/unit/test_paths.py",
    "tests/unit/test_config_loader.py",
    "tests/unit/test_logging_utils.py",
    "tests/unit/test_system_utils.py",
    "tests/unit/test_imports.py",
]


def test_required_project_directories_exist() -> None:
    for relative_path in REQUIRED_DIRECTORIES:
        assert (PROJECT_ROOT / relative_path).is_dir(), relative_path


def test_required_project_entrypoints_exist() -> None:
    for relative_path in REQUIRED_FILES:
        assert (PROJECT_ROOT / relative_path).is_file(), relative_path
