<script setup>
import {nextTick,onMounted,ref,watch} from 'vue'
import {ElMessage} from 'element-plus'
import {api} from '../api'
import {useUiStore} from '../stores/ui'
import {agentLine,agentStatus,assistantPayload} from '../utils/agentDisplay'
import {errorMessage} from '../utils/labels'
const questions=['今日有哪些 PPE 违规？','统计最近的安全事件','有哪些未戴安全帽事件？','总结当前安全风险'],dates=ref([]),input=ref(''),messages=ref([]),busy=ref(false),service=ref(null),error=ref('')
async function loadService(){try{service.value=await api.capabilities()}catch(e){error.value=errorMessage(e)}}
onMounted(loadService);watch(()=>useUiStore().refreshKey,loadService)
const chat=ref()
watch(()=>messages.value.length,async()=>{await nextTick();chat.value?.scrollTo({top:chat.value.scrollHeight})})
async function send(question=input.value){if(busy.value||!question.trim())return;const q=question.trim();messages.value.push({role:'user',text:q});input.value='';busy.value=true;try{const p=assistantPayload(q,dates.value);messages.value[messages.value.length-1].period=p.start_at?`${new Date(p.start_at).toLocaleString('zh-CN')} 至 ${new Date(p.end_at).toLocaleString('zh-CN')}`:'全部已持久化事件';const answer=await api.ask(p);messages.value.push({role:'assistant',...answer})}catch(e){messages.value.push({role:'assistant',text:errorMessage(e),error:true});ElMessage.error(errorMessage(e))}finally{busy.value=false}}
</script><template><section class="assistant-page"><div class="page-head"><div><h1>安全助手</h1><p>基于已持久化事件的只读安全查询</p></div><el-tag type="info">只读模式</el-tag></div><div class="grid-2 assistant-grid"><div class="card assistant-chat-card"><div ref="chat" class="chat"><div v-if="!messages.length" class="empty">请输入关于 PPE 事件的问题，回答会展示实际可用的数据引用。</div><div v-for="(message,i) in messages" :key="i" class="bubble" :class="message.role"><template v-if="message.role==='user'">{{message.text}}<small class="message-period">查询范围：{{message.period}}</small></template><template v-else><p :class="{error:message.error}">{{agentLine(message.answer||message.text)}}</p><div v-if="message.summary?.length"><strong>查询结果</strong><p v-for="(line,j) in message.summary" :key="j">{{agentLine(line)}}</p></div><div v-if="message.evidence_references?.length"><strong>数据来源</strong><p><el-tag v-for="ref in message.evidence_references" :key="ref" style="margin:3px">{{ref}}</el-tag></p></div><small class="muted">{{agentStatus(message.safe_status)}}</small></template></div><div v-if="busy" class="bubble assistant muted">正在执行受控查询，请稍候…</div></div><div class="composer"><el-input v-model="input" placeholder="询问安全事件、统计或证据…" style="flex:1" maxlength="2000" @keyup.enter="send()"/><el-button type="primary" :loading="busy" :disabled="!input.trim()" @click="send()">发送</el-button></div></div><div class="stack assistant-side"><div class="card"><h2>快捷提问</h2><div class="quick"><button v-for="q in questions" :key="q" :disabled="busy" @click="send(q)">{{q}} →</button></div></div><div class="card"><h2>日期范围</h2><el-date-picker v-model="dates" :disabled="busy" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" style="max-width:100%"/></div><div class="card"><h2>查询依据与服务状态</h2><p>支持“最近5分钟之内有什么安全事件”等最近 7 天内查询；手动日期范围优先。仅查询已持久化事件，不代表视频历史回放。</p><p v-if="service">监控能力：{{service.monitoring?'可用':'不可用'}}<br>模型配置：{{service.provider_configured?'已配置':'本地查询/降级'}}</p><el-alert v-if="error" type="error" :title="error" :closable="false"/></div></div></div></section></template>
