<script setup>
import {computed,onMounted,ref,watch} from 'vue'
import {ElMessage} from 'element-plus'
import {api} from '../api'
import {useUiStore} from '../stores/ui'
watch(()=>useUiStore().refreshKey,loadStats)
import {typeName,distribution,errorMessage} from '../utils/labels'
import {donutOption} from '../utils/charts'
import {agentLine,agentStatus} from '../utils/agentDisplay'
import EChart from '../components/charts/EChart.vue'
const dates=ref([]),report=ref(null),stats=ref(null),loading=ref(false),error=ref(''),zoom=ref(false),zoomEventId=ref(''),imageErrors=ref({})
async function loadStats(){try{const p=dates.value?.length?{start_at:dates.value[0],end_at:dates.value[1]}:{};stats.value=await api.statistics(p)}catch(e){error.value=errorMessage(e)}}
async function generate(){if(!dates.value?.length){ElMessage.warning('请选择报告日期范围');return}loading.value=true;error.value='';report.value=null;imageErrors.value={};try{report.value=await api.report({start_at:dates.value[0],end_at:dates.value[1]});await loadStats()}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
function openImage(eventId){zoomEventId.value=eventId;zoom.value=true}
onMounted(loadStats)
const localizedSummary=computed(()=>report.value?.summary?.map(agentLine).filter(line=>/[\u4e00-\u9fff]/.test(line))||[])
const localizedRecommendations=computed(()=>report.value?.recommendations?.map(agentLine).filter(line=>/[\u4e00-\u9fff]/.test(line))||[])
const untranslated=computed(()=>[...(report.value?.summary||[]),...(report.value?.recommendations||[])].filter(line=>!/[\u4e00-\u9fff]/.test(agentLine(line))))
const types=computed(()=>distribution(stats.value?.by_type)),pie=computed(()=>donutOption(types.value))
const mode=computed(()=>report.value?.safe_status?.includes(' / degraded /')||report.value?.safe_status?.includes('TEMPLATE_FALLBACK')?'本地模板降级':report.value?.safe_status?.includes('success')?'Provider 已验证':report.value?'报告不可用':'尚未生成')
</script><template><div class="page-head"><div><h1>AI 安全报告</h1><p>根据已持久化的 PPE 事件生成有依据的分析与整改建议</p></div><div class="filters" style="margin:0"><el-date-picker v-model="dates" :disabled="loading" @change="report=null;loadStats()" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/><el-button type="primary" :loading="loading" @click="generate">生成安全报告</el-button><el-tag :type="mode==='报告不可用'?'danger':'warning'">{{mode}}</el-tag></div></div><el-alert v-if="error" type="error" :title="error" :closable="false"/><div class="grid-2"><div class="card" v-loading="loading"><el-empty v-if="!report" :description="loading?'正在生成并校验报告，请稍候…':'请选择时间范围并生成报告'"/><template v-else><h2>工地 PPE 安全分析报告</h2><p class="muted">统计范围：{{dates?.join(' 至 ')}}</p><el-divider/><h2>安全事件概况</h2><p>{{report.answer}}</p><div v-if="localizedSummary.length" class="section-gap"><h2>主要违规问题与分析</h2><p v-for="(line,i) in localizedSummary" :key="i">{{agentLine(line)}}</p></div><div v-if="localizedRecommendations.length" class="section-gap"><h2>整改建议</h2><ol><li v-for="(line,i) in localizedRecommendations" :key="i">{{agentLine(line)}}</li></ol></div><el-collapse v-if="untranslated.length" class="section-gap"><el-collapse-item title="查看尚未中文适配的已校验原文" name="original"><p class="muted">以下原文保留原有依据校验结果，尚未进行中文转换。</p><p v-for="(line,i) in untranslated" :key="i">{{line}}</p></el-collapse-item></el-collapse><div class="section-gap"><h2>数据依据</h2><p class="muted">仅展示报告引用且通过服务端完整性校验的事件抓拍。</p><el-empty v-if="!report.evidence_images?.length" description="此报告暂无可显示的已校验证据图片"/><div v-else class="report-evidence-grid"><div v-for="item in report.evidence_images" :key="item.event_id" class="report-evidence-item"><div v-if="imageErrors[item.event_id]" class="report-evidence-error">证据图片当前不可用</div><button v-else type="button" class="report-evidence-button" :aria-label="`放大事件 ${item.event_id} 的证据`" @click="openImage(item.event_id)"><img :src="api.image(item.event_id)" :alt="`事件 ${item.event_id} 的证据`" loading="lazy" @error="imageErrors[item.event_id]=true"/></button><small>{{item.event_id}}</small></div></div></div></template></div><div class="stack"><div class="card"><h2>当前范围最新统计</h2><p class="muted">独立实时查询；报告正文使用生成时的校验数据，监控期间可能新增事件。</p><div class="metric"><div class="metric-icon">▣</div><div><small>已持久化事件</small><strong>{{stats?.total_count??'—'}}</strong></div></div><p v-for="(count,key) in stats?.by_type||{}" :key="key">{{typeName[key]||key}}：{{count}}</p></div><div class="card"><h2>事件类型分布</h2><EChart v-if="types.length" :option="pie"/><el-empty v-else description="暂无事件类型数据"/></div><div class="card"><h2>报告校验与生成方式</h2><p>{{mode}}</p><p class="muted">{{report?agentStatus(report.safe_status):'报告尚未生成'}}</p><p>报告内容由原有受控 Agent、Grounding Validator 和模板降级路径返回。</p></div></div></div><el-dialog v-model="zoom" title="证据大图" width="min(90vw,1200px)"><img v-if="zoomEventId" :src="api.image(zoomEventId)" class="report-evidence-zoom" alt="报告引用事件证据大图"/></el-dialog></template>
