<script setup>
import {onMounted,reactive,ref,watch} from 'vue'
import {useRoute,useRouter} from 'vue-router'
import {ElMessage} from 'element-plus'
import {api} from '../api'
import {useUiStore} from '../stores/ui'
watch(()=>useUiStore().refreshKey,load)
import {typeName,formatTime,errorMessage} from '../utils/labels'
const route=useRoute(),router=useRouter(),filters=reactive({event_type:'',dates:[]}),items=ref([]),selected=ref(null),loading=ref(false),error=ref(''),zoom=ref(false),page=ref(1),total=ref(0)
async function load(preferredId){loading.value=true;error.value='';try{const p={limit:50,offset:(page.value-1)*50};if(filters.event_type)p.event_type=filters.event_type;if(filters.dates?.length){p.start_at=filters.dates[0];p.end_at=filters.dates[1]}const d=await api.evidence(p);items.value=d.items;total.value=d.total_count;const target=typeof preferredId==='string'?preferredId:items.value.find(item=>item.id===selected.value?.event.id)?.id||items.value[0]?.id;if(target)await choose(target);else selected.value=null}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
let selectionRequest=0
async function choose(id){const request=++selectionRequest;selected.value=null;try{const detail=await api.evidenceItem(id);if(request===selectionRequest)selected.value=detail}catch(e){if(request===selectionRequest)ElMessage.error(errorMessage(e))}}
async function copy(){try{if(selected.value?.snapshot?.sha256){await navigator.clipboard.writeText(selected.value.snapshot.sha256);ElMessage.success('SHA256 已复制')}}catch{ElMessage.error('复制失败，请手动选择 SHA256')}}
function reset(){filters.event_type='';filters.dates=[];page.value=1;load()}
onMounted(()=>load(route.query.id))
watch(()=>route.query.id,id=>{if(typeof id==='string')choose(id)})
</script>
<template><div class="page-head"><div><h1>事件证据中心</h1><p>查看已持久化事件的抓拍证据与完整性</p></div></div><div class="card filters"><el-select v-model="filters.event_type" placeholder="违规类型" clearable style="width:160px"><el-option v-for="(name,key) in typeName" :key="key" :label="name" :value="key"/></el-select><el-date-picker v-model="filters.dates" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/><el-button type="primary" @click="page=1;load()">查询</el-button><el-button @click="reset">重置</el-button></div>
<el-alert v-if="error" class="section-gap" type="error" :title="error" :closable="false"/><div class="evidence-grid section-gap"><div class="card evidence-list-card"><h2>证据事件列表</h2><div v-loading="loading" class="event-list"><el-empty v-if="!items.length" description="暂无证据事件"/><div v-for="item in items" :key="item.id" class="event-item" :class="{selected:selected?.event.id===item.id}" @click="choose(item.id)"><strong>{{typeName[item.type]||item.type}}</strong><p>{{formatTime(item.timestamp)}}</p><small>Track ID：{{item.track_id}} · {{item.id}}</small></div></div><el-pagination v-model:current-page="page" :page-size="50" :total="total" layout="prev,pager,next" @current-change="load"/></div><div class="card"><el-empty v-if="!selected" description="请选择证据事件"/><template v-else><h2>事件证据图像</h2><el-alert v-if="!selected.verified" type="error" :title="selected.error||'证据不可用或校验失败'" :closable="false"/><img v-if="selected.verified" :src="api.image(selected.event.id)" class="evidence-image" alt="已校验证据" @click="zoom=true" style="cursor:zoom-in"/><div class="section-gap"><el-button v-if="selected.verified" @click="zoom=true">放大图片</el-button><el-button @click="router.push({path:'/events',query:{id:selected.event.id}})">查看关联事件</el-button></div><h2 class="section-gap">事件元数据</h2><el-descriptions :column="2" border><el-descriptions-item label="事件编号">{{selected.event.id}}</el-descriptions-item><el-descriptions-item label="发生时间">{{formatTime(selected.event.timestamp)}}</el-descriptions-item><el-descriptions-item label="违规类型">{{typeName[selected.event.type]||selected.event.type}}</el-descriptions-item><el-descriptions-item label="Track ID">{{selected.event.track_id}}</el-descriptions-item><el-descriptions-item label="图像尺寸">{{selected.snapshot?`${selected.snapshot.width} × ${selected.snapshot.height}`:'—'}}</el-descriptions-item><el-descriptions-item label="完整性">{{selected.verified?'服务端校验通过':'未通过'}}</el-descriptions-item><el-descriptions-item label="SHA256" :span="2"><span style="word-break:break-all">{{selected.snapshot?.sha256||'—'}}</span><el-button v-if="selected.snapshot?.sha256" link type="primary" @click="copy">复制</el-button></el-descriptions-item></el-descriptions></template></div></div>
<el-dialog v-model="zoom" title="证据大图" width="min(90vw,1200px)"><img v-if="selected?.verified" :src="api.image(selected.event.id)" style="width:100%" alt="证据大图"/></el-dialog></template>
