<script setup>
import {computed,onMounted,ref,watch} from 'vue'
import {useRouter} from 'vue-router'
import {api} from '../api'
import {useUiStore} from '../stores/ui'
import {typeName,statusName,formatTime,distribution,errorMessage} from '../utils/labels'
import MetricCard from '../components/common/MetricCard.vue'
import {donutOption} from '../utils/charts'
import EChart from '../components/charts/EChart.vue'
const router=useRouter(),ui=useUiStore(),dates=ref([]),data=ref(null),loading=ref(false),error=ref('')
async function load(){loading.value=true;error.value='';try{const p=dates.value?.length?{start_at:dates.value[0],end_at:dates.value[1]}:{};data.value=await api.overview(p)}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
onMounted(load);watch(()=>ui.refreshKey,load)
const stats=computed(()=>data.value?.statistics||{}),types=computed(()=>distribution(stats.value.by_type)),days=computed(()=>Object.entries(stats.value.by_day||{}).sort())
const trend=computed(()=>({tooltip:{trigger:'axis'},grid:{left:10,right:20,top:25,bottom:10,containLabel:true},xAxis:{type:'category',data:days.value.map(x=>x[0])},yAxis:{type:'value',minInterval:1},series:[{type:'line',smooth:false,areaStyle:{opacity:.12},data:days.value.map(x=>x[1]),lineStyle:{color:'#2563eb'},itemStyle:{color:'#2563eb'}}]}))
const donut=computed(()=>donutOption(types.value))
</script>
<template><div class="page-head"><div><h1>安全运营总览</h1><p>基于已持久化 PPE 事件的安全态势</p></div><div class="filters" style="margin:0"><el-date-picker v-model="dates" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/><el-button type="primary" @click="load">查询</el-button></div></div><el-alert v-if="error" type="error" :title="error" :closable="false"/><div v-loading="loading"><div class="grid-4"><MetricCard label="累计事件" :value="stats.total_count??'—'" icon="▣"/><MetricCard label="待处理事件" :value="stats.by_status?.open??0" icon="◷"/><MetricCard label="未戴安全帽" :value="stats.by_type?.NO_HELMET??0" icon="⛑"/><MetricCard label="未穿反光衣" :value="stats.by_type?.NO_VEST??0" icon="⚠"/></div><div class="grid-2 section-gap"><div class="card"><h2>事件变化趋势</h2><EChart v-if="days.length" :option="trend"/><el-empty v-else description="所选时段暂无事件"/></div><div class="card"><h2>违规类型分布</h2><EChart v-if="types.length" :option="donut"/><el-empty v-else description="暂无类型分布"/></div></div><div class="grid-2 section-gap"><div class="card"><h2>近期安全事件</h2><el-table :data="data?.recent_events||[]" empty-text="暂无事件"><el-table-column label="发生时间" min-width="165"><template #default="{row}">{{formatTime(row.timestamp)}}</template></el-table-column><el-table-column label="类型" min-width="125"><template #default="{row}">{{typeName[row.type]||row.type}}</template></el-table-column><el-table-column label="状态" min-width="90"><template #default="{row}">{{statusName[row.status]||row.status}}</template></el-table-column><el-table-column label="操作" width="70"><template #default="{row}"><el-button link type="primary" @click="router.push({path:'/events',query:{id:row.id}})">查看</el-button></template></el-table-column></el-table></div><div class="stack"><div class="card"><h2>快捷入口</h2><div class="grid-even"><el-button @click="router.push('/monitoring')">实时监控</el-button><el-button @click="router.push('/events')">事件中心</el-button><el-button @click="router.push('/evidence')">证据中心</el-button><el-button @click="router.push('/ai-report')">生成安全报告</el-button></div></div><div class="card"><h2>系统状态</h2><p>统计数据来自已持久化事件；PPE 状态未知事件 {{stats.by_type?.PPE_UNKNOWN??0}} 条。</p><p class="muted">事件数量不能推导全工地 PPE 合规率。</p></div></div></div></div></template>
