<script setup>
import {computed,onMounted,ref,watch} from 'vue'
import {api} from '../api'
import {useUiStore} from '../stores/ui'
import {typeName,statusName,distribution,errorMessage} from '../utils/labels'
import MetricCard from '../components/common/MetricCard.vue'
import {donutOption} from '../utils/charts'
import EChart from '../components/charts/EChart.vue'
const ui=useUiStore(),dates=ref([]),filterType=ref(''),filterStatus=ref(''),data=ref(null),loading=ref(false),error=ref('')
async function load(){loading.value=true;error.value='';try{const p={};if(dates.value?.length){p.start_at=dates.value[0];p.end_at=dates.value[1]}if(filterType.value)p.event_type=filterType.value;if(filterStatus.value)p.status=filterStatus.value;data.value=await api.statistics(p)}catch(e){error.value=errorMessage(e)}finally{loading.value=false}}
function reset(){dates.value=[];filterType.value='';filterStatus.value='';load()}
onMounted(load);watch(()=>ui.refreshKey,load)
const days=computed(()=>Object.entries(data.value?.by_day||{}).sort()),types=computed(()=>distribution(data.value?.by_type)),statuses=computed(()=>distribution(data.value?.by_status)),sources=computed(()=>distribution(data.value?.by_source))
const axis={axisLabel:{color:'#718096'}}
const line=computed(()=>({tooltip:{trigger:'axis'},legend:{data:['总事件']},grid:{left:10,right:20,top:35,bottom:10,containLabel:true},xAxis:{type:'category',data:days.value.map(x=>x[0]),...axis},yAxis:{type:'value',minInterval:1,...axis},series:[{name:'总事件',type:'line',data:days.value.map(x=>x[1]),smooth:false,itemStyle:{color:'#2563eb'}}]}))
const pie=computed(()=>donutOption(types.value))
const bar=(items,horizontal=false)=>({tooltip:{trigger:'axis'},grid:{left:10,right:20,top:20,bottom:10,containLabel:true},xAxis:horizontal?{type:'value',minInterval:1}:{type:'category',data:items.map(x=>x.name),axisLabel:{interval:0}},yAxis:horizontal?{type:'category',data:items.map(x=>x.name)}:{type:'value',minInterval:1},series:[{type:'bar',data:items.map(x=>x.value),itemStyle:{color:'#3284f4'}}]})
</script><template><div class="page-head"><div><h1>安全统计分析</h1><p>基于已确认并持久化事件的趋势分析</p></div></div><div class="card filters"><el-date-picker v-model="dates" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/><el-select v-model="filterType" clearable placeholder="事件类型" style="width:150px"><el-option v-for="(name,key) in typeName" :key="key" :label="name" :value="key"/></el-select><el-select v-model="filterStatus" clearable placeholder="处理状态" style="width:150px"><el-option v-for="(name,key) in statusName" :key="key" :label="name" :value="key"/></el-select><el-button type="primary" @click="load">查询</el-button><el-button @click="reset">重置</el-button></div><el-alert v-if="error" type="error" :title="error" :closable="false"/><div v-loading="loading"><div class="grid-4 section-gap"><MetricCard label="总事件" :value="data?.total_count??'—'" icon="▣"/><MetricCard label="未戴安全帽" :value="data?.by_type?.NO_HELMET??0" icon="⛑"/><MetricCard label="未穿反光衣" :value="data?.by_type?.NO_VEST??0" icon="⚠"/><MetricCard label="PPE 状态未知" :value="data?.by_type?.PPE_UNKNOWN??0" icon="?"/></div><div class="grid-2 section-gap"><div class="card"><h2>每日事件趋势</h2><EChart v-if="days.length" :option="line"/><el-empty v-else description="暂无趋势数据"/></div><div class="card"><h2>违规类型分布</h2><EChart v-if="types.length" :option="pie"/><el-empty v-else description="暂无类型数据"/></div></div><div class="grid-even section-gap"><div class="card"><h2>事件处理状态分布</h2><EChart v-if="statuses.length" :option="bar(statuses,true)"/><el-empty v-else description="暂无状态数据"/></div><div class="card"><h2>输入来源统计</h2><EChart v-if="sources.length" :option="bar(sources)"/><el-empty v-else description="暂无来源数据"/></div></div><p class="muted">所有分布以所选范围内已持久化事件总数为分母；图表不代表工地人员合规率。</p></div></template>
